### PR TITLE
Upgrade and reduce the usage of lodash

### LINKED ISSUE #135: Security issues
I'm thinking about including this project in our repo, but notice on install several security warnings from npm:

Screen Shot 2021-02-02 at 20 17 34

This makes me wonder if the library is maintained - or maybe needs help maintaining?

### PR DESCRIPTION
**Pull request by alexbjorlig**
# Objective --> remove lodash security warnings
The primary objective of this PR is to remove security warnings when using the library (maybe we can setup [snyk.io](https://snyk.io/) later to warn about this?)

## What changed
Simply upgrading lodash was not easy at all, and gave a tremendous amount of errors because a lot of functions were re-named or their API was modified.

In response to this, I converted must lodash functions to just using Node.js.

However there are 2 functions left:

- `_.get()`
- `_.defaultsDeep()`

I think `get` can be easily removed, when we upgrade the repo to Node.js `v14`, because then we can use `?.` and `??` syntax. I'm not so sure about `defaultsDeep`.

But I decided to finish up the PR because, **hey it works and Lodash is updated to the latest version** 💃🏾    🚀

## Positive side-effects

I actually think the source code will be more easy to read with the reduced usage of lodash.

Closes #135

### CODE REVIEW

**Comment by alexbjorlig** [comment]
This is a rather big PR - almost done (still working on some small issues with Travis).

Because of the refactor to modern js --> the old way of using istanbul and mocha was failing in CI. I therefore also updated their API according to newest documentation (the istanbul CLI might not have been around back in the days ☺️).

I hope it will be passing soon.

**Comment by alexbjorlig** [comment]
@addaleax can you maybe take a look at why the CI process fails?

**Comment by addaleax** [comment]
I don’t know, it seems like just re-pushing might help? (I can’t restart the Travis workflow myself.)

Also, if you want, you can PR the Github Workflow separately. I’m not sure if Github needs to have one present on the master branch in order to work, but if that works, we can just remove Travis entirely (which we’ve been doing for other repositories as well).

**Comment by alexbjorlig** [comment]
> I don’t know, it seems like just re-pushing might help? (I can’t restart the Travis workflow myself.)
> 
> Also, if you want, you can PR the Github Workflow separately. I’m not sure if Github needs to have one present on the master branch in order to work, but if that works, we can just remove Travis entirely (which we’ve been doing for other repositories as well).

Sounds like a good plan - here is the pr with only the updated ci / github workflow #144  ✅

**Comment by alexbjorlig** [comment]
> I don’t know, it seems like just re-pushing might help? (I can’t restart the Travis workflow myself.)
> 
> Also, if you want, you can PR the Github Workflow separately. I’m not sure if Github needs to have one present on the master branch in order to work, but if that works, we can just remove Travis entirely (which we’ve been doing for other repositories as well).

PR incoming wo😅

**Pull request closed without merging**
