### PR TITLE
INT-476 benchmarking

### PR DESCRIPTION
**Pull request by rueckstiess**
Progress on the schema performance tweaks. 10,000 fanclub docs in 2 seconds, vs. 28 seconds before.

```
$ DEBUG=mongodb-schema:parse2 ./bin/mongodb-schema.js localhost:27017 mongodb.fanclub -n 10000 --stats --no-output --fast
time: 2045ms
toplevel fields: 10
branching factors: [10,5,2]
schema width: 17
schema depth: 3
```

However, with some caveats, like still only storing 100 example values per field, rather than all 10,000. 

To compare, try above command with and without the `--fast` option.

This version uses `./lib/parse2.js` rather than the first attempt `./lib/parse.js`. parse2 is even shorter and works without reduce step because it updates a schema document in place. 

After the parsing is complete, the schema is revived with a `model.set(schema, {parse: true})` call, which recursively creates and populates all the models inside a schema. 

See also `./test/revive.test.js`.

[Review on Reviewable](https://reviewable.io/reviews/mongodb-js/mongodb-schema/28)

### CODE REVIEW

**Comment by rueckstiess** [comment]
I'd like to propose a backwards-breaking change and get some feedback on it (@imlucas).

`Schema` has a stream interface, which is implemented as a through stream, i.e. it reads documents from a readable stream (e.g. file, cursor, sampler), analyses each doc and integrates information into the schema object, and pipes the document to a successor writeable stream. 

I'd like to change the interface so that the schema stream no longer emits individual documents but instead waits until the `end` event and then writes a single output, which is the schema. 

Reasons:
- It would allow to post-process the resulting schema in stream-like fashion, by piping the result to a `finalizer` stream.
- Would make the switch between "fast" parsing (see `./lib/parse2.js`) and normal parsing (see `./lib/schema.js) easier.
- Anyone interested in the stream of individual objects can still "tab into" the stream before the schema stream via a through stream.

Any objections?

**Comment by rueckstiess** [comment]
#### Code Review

This is now ready to be reviewed. Notable changes:

- there is now a `./lib/parse-native.js` file that implements the fast native js parser
- it is used in `./lib/schema.js` in the `Schema#stream` method. A flag is currently used to switch between the two behaviors until we can be sure the fast parsing algorithm can fully replace the original one.
- There is a binary in `./bin/mongodb-schema.js` that can return documents in json, yaml, table format, can also run multiple experiments and return execution time statistics. See `--help`.
- Tests added to verify new parser is identical to old one
- Backwards-breaking behavior: `Schema#stream` now outputs a single `data` event at the end, the schema itself. It also has a `progress` event that is triggered after each document.

**Comment by kangas** [comment]
+1 to this change as described above. I have not yet reviewed the code.

**Comment by imlucas** [comment]
Sorry for making you wait so long on this :(  The new parsing is fantastic!  Left some notes but I think some further refactoring could be done here if we're going to make any breaking changes.  Let's discuss more in standup   For example, when it comes to streams/ampersand, it would make this codebase much leaner/maintainable/reliable in the future if those were handled outside of this core `mongodb-schema` module in say `ampersand-mongodb-schema`.

---

Reviewed 1 of 1 files at r1, 17 of 25 files at r3, 6 of 7 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[package.json, line 4 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiQehmh-oZoWKo7rHb:-KBiQehmh-oZoWKo7rHc:-1267538181) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L4)):*
version changes should only be done after a PR is merged into master

---

*[package.json, line 36 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiR0YEl0MyeT0Xs79P:-KBiR0YEl0MyeT0Xs79Q:1924658766) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L36)):*
See docs https://github.com/mongodb-js/precommit#dependency-check

These should not be ignored.  You should add the entrypoints which use these instead.  Believe the following will give you the intended result`"entries": ["bin/mongodb-schema.js", "index.js"]`

---

*[package.json, line 45 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiRe4J4E7mYQ4qJxB2:-KBiRe4J4E7mYQ4qJxB3:-1352712633) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L45)):*
pinning the version here without a comment as to why feels like a landmine that will lead to a difficult problem to root cause.

---

*[package.json, line 49 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiS6JOe_uc1rR6WDkj:-KBiS6JOe_uc1rR6WDkk:85363753) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L49)):*
Should be an optional dependency as the driver will cause issues downstream for folks using browserify et al (causes a difficult to resolve "wtf am I getting this weird build exception now?").  

Alternatively, you could add `mongodb-connection-model` as a dependency; properly encapsulates the logic you're looking for and handles the weird browserify case mentioned above.

---

*[package.json, line 73 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiPkwwscKWQyx28hNT:-KBiPkwwscKWQyx28hNU:-1261886923) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L73)):*
don't believe you intended to commit this

---

*[bin/mongodb-schema.js, line 33 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiTEtkO6l4OYPhCBuU:-KBiTEtkO6l4OYPhCBuV:-541131955) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/bin/mongodb-schema.js#L33)):*
quite confused by adding all of these extra options for output... this is a `bin` script.  why not just output dependent on the output format option?

---

*[bin/mongodb-schema.js, line 51 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiT7DWBDdqeYLQVUl1:-KBiT7DWBDdqeYLQVUl2:-1805603934) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/bin/mongodb-schema.js#L51)):*
renamed to native?

---

*[docs/schema-stats.md, line 2 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiTt96wBm5ceQnIxLD:-KBiTt96wBm5ceQnIxLE:-1583716212) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/docs/schema-stats.md#L2)):*
This is fantastic!  Please move into the top-level README.md

---

*[examples/parse-from-file.js, line 12 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiUDF8N9dXTPvnz9ue:-KBiUDF8N9dXTPvnz9uf:-1026730133) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/examples/parse-from-file.js#L12)):*
why is this using `process.argv` directly?  perhaps you mean to add a `--file` option to `bin/mongodb-schema.js` instead?  examples should be self contained (e.g. here you would have a json file checked in under examples this js points to).

---

*[examples/parse-schema.js, line 4 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiUnWOOqrQFmx2lytW:-KBiUnWPFadQO6SM4O4U:-309353576) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/examples/parse-schema.js#L4)):*
im again quite confused.... are these are so you can do benchmarking?  If so, they should be under `benchmarks` not `examples`.

---

*[lib/index.js, line 11 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiVJVZD9-ZfrBzb4UA:-KBiVJVZD9-ZfrBzb4UB:1391870952) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/lib/index.js#L11)):*
if you're confident in `fast/native`, don't make it yet another option :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-:-KBiXWSpT0ynz6nUvoMG:-1558659045)*

**Comment by rueckstiess** [comment]
Agree, but sounds like a significant refactoring step. Can we do this as a separate issue after the parsing changes are merged in?

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[package.json, line 45 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiRe4J4E7mYQ4qJxB2:-KBjLbgzJ6LWhfJOzkOd:-1654858366) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L45)):*
do you suggest a comment via `"//": "comment"` syntax, or to undo the pinning? I think I favour pinning+comment.

---

*[package.json, line 49 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiS6JOe_uc1rR6WDkj:-KBjMFSCFkkjDj0B1_tA:322182774) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L49)):*
I'll make it an optional dependency.

---

*[package.json, line 73 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiPkwwscKWQyx28hNT:-KBjMJQz4akOUvhrhSnX:33075857) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/package.json#L73)):*
correct. will fix :)

---

*[examples/parse-from-file.js, line 12 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiUDF8N9dXTPvnz9ue:-KBjOfYvDgdSaq12FS30:456882154) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/examples/parse-from-file.js#L12)):*
ok, removed `process.argv` and added example json file, which is now being loaded.

---

*[examples/parse-schema.js, line 4 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiUnWOOqrQFmx2lytW:-KBjOviJQKO48Dx73tIi:198287770) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/examples/parse-schema.js#L4)):*
Yes I was using these to benchmark, sorry shouldn't have made it in. I'm just going to revert all changes to this file. 

---

*[lib/index.js, line 11 \[r4\]](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-KBiVJVZD9-ZfrBzb4UA:-KBjPayc-NYeWzuhI4w9:741050952) ([raw file](https://github.com/mongodb-js/mongodb-schema/blob/b738fbdc67056e8a0fc904d1ac3674c89b3ed4e7/lib/index.js#L11)):*
I'll remove the option here, but I'd like it to be an option in the actual stream, e.g. 

```js
var schema = new Schema();
var useNativeParser = true;  // or switch to false
schema.stream(useNativeParser);
```

This is so we can easily benchmark both versions. We can remove the switch in the next version.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-:-KBjQKwGuvVGrkmFUQ_3:-1463326329)*

**Comment by imlucas** [comment]
@rueckstiess re: refactoring as sep. pull request sounds good to me.  :lgtm_strong: 

---

Review status: 17 of 23 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-schema/28#-:-KBkXQikz6cmZtUjKVWl:-1869146109)*

**Pull request merged**
